[manager]
show_hidden = true
show_symlink = true
ratio = [0, 4, 0]

[opener]
edit = [
  { run = 'tmux send-keys -t 2 Escape "\:open $1" ENTER && tmux select-pane -t 2', desc = "Open file in Helix pane" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
