[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]
shebangs = ["python"]
comment-token = "#"

[language.formatter]
command = "black"
args = [
"-", # stdin
"--quiet",
"--line-length=79",
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config]
settings = {args = []}
