
[window]

opacity = 0.93
blur = true
dynamic_title = true

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "MesloLGL Nerd Font"
bold.family = "MesloLGL Nerd Font"
italic.family = "MesloLGL Nerd Font"
bold_italic.family = "MesloLGL Nerd Font"
size = 13.0

[cursor]
style = "Beam"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control|Shift"

[general]

live_config_reload = true
# $HOME/.config/alacritty/alacritty.toml

import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
